server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nuwan199044/spring-cloud-config-store
          search-paths:
           - '*service'



